reviewers:
  - avidan-H
bot_name: my-first-appp
owner: avidan-H
repo: bot-working
# days, hours, and minutes are added together
days: 0 # Number of days until PR is considered stale
hours: 0 # Number of hours until PR is considered stale
minutes: 1 # Number of minutes until PR is considered stale